version: 0.2
#Subtitute of action yml file
phases:
  install:
    runtime-versions:
      docker: 18
    commands:                                                                 
      - make install
  build:
    commands:
      - make lint
      - make test
  post_build:
    commands:
      - echo Testing completed `date`
